name: Set Environment

inputs:
  xcode-version:
    required: true
    type: string
  
runs:
  using: "composite"
  steps:
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_${{ inputs.xcode-version }}.app/Contents/Developer
      shell: bash
    - name: Show macOS version
      run: sw_vers
      shell: bash
    - name: Check xcodebuild version
      run: xcodebuild -version
      shell: bash
