name: Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

env:
  SCHEME: 'EC2macConnector'
  XCODE_VERSION: '14.3.0'

jobs:
  build:
    runs-on: 'macos-13'
    strategy:
      fail-fast: false
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3  
      - name: Common steps
        uses: ./.github/actions/common_steps
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - name: Build
        working-directory: ./
        run: xcodebuild build -scheme ${{ env.SCHEME }} -destination "platform=macOS"
