name: Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

env:
  TOOL_NAME: 'EC2macConnector'
  XCODE_VERSION: '14.2.0'

jobs:
  build:
    runs-on: 'macos-12'
    strategy:
      fail-fast: false
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3  
      - name: Common steps
        uses: ./.github/actions/common_steps
        with:
          tool-name: ${{ env.TOOL_NAME }}
          xcode-version: ${{ env.XCODE_VERSION }}
      - name: Build
        working-directory: ./
        run: xcodebuild build -scheme EC2macConnector -destination "platform=macOS"
