name: Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

env:
  XCODE_VERSION: '14.3.0'

jobs:
  build:
    name: Build for debug
    runs-on: 'macos-13'
    strategy:
      fail-fast: false
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3  
      - name: Set Environment
        uses: ./.github/actions/set_environment
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - name: Build
        working-directory: ./
        run: swift build -c debug
