name: Release

on:
  push:
    tags:
      - '*'

env:
  XCODE_VERSION: '14.2.0'

jobs:
  build:
    runs-on: 'macos-12'
    strategy:
      fail-fast: false
    steps:
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app/Contents/Developer
      - name: Show macOS version
        run: sw_vers
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Check xcodebuild version
        run: xcodebuild -version
      - name: Check xcode embedded SDKs
        run: xcodebuild -showsdks
      - name: Show buildable schemes
        working-directory: ./
        run: xcodebuild -list
      - name: Build products for release
        working-directory: ./
        run: swift build -c release --arch arm64 --arch x86_64
      - name: Zip executable
        working-directory: .build/apple/Products/Release/
        run: zip -r ec2macConnector.zip ec2macConnector
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .build/apple/Products/Release/ec2macConnector.zip
          asset_name: ec2macConnector.zip
          asset_content_type: application/zip
        